create table phone (id bigint generated by default as identity, citycode varchar(255), countrycode varchar(255), number varchar(255), primary key (id))
create table role (id bigint generated by default as identity, description varchar(255), role_name varchar(255), primary key (id))
create table user (id binary not null, created timestamp, email varchar(255) not null, is_active boolean, last_login timestamp, modified timestamp, name varchar(255) not null, password varchar(255) not null, token varchar(255), username varchar(255), primary key (id))
create table user_phones (user_id binary not null, phones_id bigint not null)
create table user_role (user_id binary not null, role_id bigint not null)
alter table user_phones add constraint UK_lpx6wawt7f9hqolfy260iava4 unique (phones_id)
alter table user_phones add constraint FK8a99k1bvo4hgvib6t1ui8riob foreign key (phones_id) references phone
alter table user_phones add constraint FKdfslj94kbjqvp71kjjc36iije foreign key (user_id) references user
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user